import { Category, Product, GalleryImage } from './supabase/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name_az: 'İsti İçkilər',
    name_en: 'Hot Drinks',
    name_ru: 'Горячие напитки',
    slug: 'hot-drinks',
    display_order: 1,
  },
  {
    id: 'cat-2',
    name_az: 'Soyuq və Xüsusi',
    name_en: 'Cold & Specialty',
    name_ru: 'Холодные и спешелти',
    slug: 'cold-drinks',
    display_order: 2,
  },
  {
    id: 'cat-3',
    name_az: 'Manual Brew & Filter',
    name_en: 'Manual Brew & Filter',
    name_ru: 'Фильтр и альтернатива',
    slug: 'filter-coffee',
    display_order: 3,
  },
  {
    id: 'cat-4',
    name_az: 'Xüsusi Desertlər',
    name_en: 'Artisan Desserts',
    name_ru: 'Авторские десерты',
    slug: 'desserts',
    display_order: 4,
  },
  {
    id: 'cat-5',
    name_az: 'Səhər Yeməyi & Bites',
    name_en: 'Breakfast & Bites',
    name_ru: 'Завтраки и перекусы',
    slug: 'breakfast',
    display_order: 5,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-featured-1',
    category_id: 'cat-2',
    name_az: 'RoastBar Signature Pistachio Latte',
    name_en: 'RoastBar Signature Pistachio Latte',
    name_ru: 'Фирменный Фисташковый Латте',
    description_az: 'Xüsusi qovrulmuş tək mənşəli espresso, ipək kimi köpükləndirilmiş süd və təbii püstə pastası ilə hazırlanmış imza içkisi.',
    description_en: 'Our signature specialty espresso blended with velvety textured milk and 100% natural Sicilian pistachio paste.',
    description_ru: 'Наш авторский спешелти эспрессо с бархатным молоком и натуральной сицилийской фисташковой пастой.',
    base_price: 8.5,
    sizes: [
      { name: 'Regular', volume: '350ml', price: 8.5 },
      { name: 'Large', volume: '450ml', price: 9.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80',
    is_featured: true,
    is_available: true,
    tags: ['Signature', 'Best Seller', 'Barista Pick'],
    display_order: 1,
  },
  {
    id: 'prod-2',
    category_id: 'cat-1',
    name_az: 'Flat White',
    name_en: 'Flat White',
    name_ru: 'Флэт Уайт',
    description_az: 'İkiqat ristretto və xırda məsaməli mikro-köpüklü südün balanslı harmoniyası.',
    description_en: 'Double shot ristretto with silky microfoam milk for a rich, intense coffee forward taste.',
    description_ru: 'Двойной шот ристретто с идеальной шелковистой микропенкой.',
    base_price: 6.0,
    sizes: [
      { name: 'Standard', volume: '200ml', price: 6.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80',
    is_featured: false,
    is_available: true,
    tags: ['Classic', 'Specialty'],
    display_order: 2,
  },
  {
    id: 'prod-3',
    category_id: 'cat-1',
    name_az: 'Spanish Cortado',
    name_en: 'Spanish Cortado',
    name_ru: 'Испанский Кортадо',
    description_az: 'Espresso və qatılaşdırılmış südün bərabər nisbətdə mükəmməl vəhdəti.',
    description_en: 'Rich espresso cut with an equal amount of warm textured milk and a touch of condensed milk.',
    description_ru: 'Насыщенный эспрессо со вспененным молоком и нежной ноткой сгущенного молока.',
    base_price: 5.5,
    sizes: [
      { name: 'Standard', volume: '150ml', price: 5.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    is_featured: false,
    is_available: true,
    tags: ['Popular'],
    display_order: 3,
  },
  {
    id: 'prod-4',
    category_id: 'cat-1',
    name_az: 'Cappuccino Crema',
    name_en: 'Cappuccino Crema',
    name_ru: 'Капучино Крема',
    description_az: 'Dərin espresso bazası, qalın qaymaqlı köpük və incə kakao tozu ilə.',
    description_en: 'A deep specialty espresso base topped with creamy dense foam and cocoa dust.',
    description_ru: 'Спешелти эспрессо с густой сливочной пенкой и щепоткой какао.',
    base_price: 6.0,
    sizes: [
      { name: 'Small', volume: '220ml', price: 6.0 },
      { name: 'Medium', volume: '320ml', price: 7.0 },
      { name: 'Large', volume: '420ml', price: 8.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80',
    is_featured: false,
    is_available: true,
    tags: ['Favorite'],
    display_order: 4,
  },
  {
    id: 'prod-5',
    category_id: 'cat-2',
    name_az: 'Cold Brew Reserve (18h Steeping)',
    name_en: 'Cold Brew Reserve (18h Steeping)',
    name_ru: 'Колд Брю Резерв (18ч заваривания)',
    description_az: 'Efiopiya Yirgacheffe dənələrindən 18 saat ərzində buzlu suda dəmlənmiş təravətləndirici soyuq qəhvə.',
    description_en: 'Single-origin Ethiopian Yirgacheffe slowly steeped in cold filtered water for 18 hours. Low acidity, floral notes.',
    description_ru: 'Моносорт Эфиопия Иргачефф медленного 18-часового холодного настаивания с нотами жасмина и бергамота.',
    base_price: 7.0,
    sizes: [
      { name: 'Glass', volume: '300ml', price: 7.0 },
      { name: 'Bottle', volume: '500ml', price: 11.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
    is_featured: false,
    is_available: true,
    tags: ['Cold Brew', 'Specialty'],
    display_order: 5,
  },
  {
    id: 'prod-6',
    category_id: 'cat-2',
    name_az: 'Iced Salted Caramel Macchiato',
    name_en: 'Iced Salted Caramel Macchiato',
    name_ru: 'Айс Соленая Карамель Маккиато',
    description_az: 'Vanil şərbəti, soyuq süd, espresso və ev üsulu duzlu karamel sousu.',
    description_en: 'Fresh espresso poured over cold milk, Madagascar vanilla, and house-made salted caramel drizzle.',
    description_ru: 'Освежающий напиток с домашней соленой карамелью, мадагаскарской ванилью и эспрессо.',
    base_price: 7.5,
    sizes: [
      { name: 'Medium', volume: '380ml', price: 7.5 },
      { name: 'Large', volume: '480ml', price: 8.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80',
    is_featured: false,
    is_available: true,
    tags: ['Sweet', 'Iced'],
    display_order: 6,
  },
  {
    id: 'prod-7',
    category_id: 'cat-3',
    name_az: 'V60 Pour Over - Geisha Panama',
    name_en: 'V60 Pour Over - Geisha Panama',
    name_ru: 'V60 Фильтр - Гейша Панама',
    description_az: 'Yapon V60 üsulu ilə dəmlənmiş tək mənşəli nadir qəhvə. Portağal çiçəyi və berqamot notları.',
    description_en: 'Handcrafted V60 brew using prize-winning Panama Geisha. Delicate floral notes, bergamot, and sweet apricot.',
    description_ru: 'Ручной пуровер V60 на редком зерне Панама Гейша с нотами персика, жасмина и цитрусовых.',
    base_price: 12.0,
    sizes: [
      { name: 'Server', volume: '250ml', price: 12.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    is_featured: false,
    is_available: true,
    tags: ['Specialty', 'Single Origin'],
    display_order: 7,
  },
  {
    id: 'prod-8',
    category_id: 'cat-4',
    name_az: 'San Sebastian Cheesecake',
    name_en: 'San Sebastian Cheesecake',
    name_ru: 'Чизкейк Сан-Себастьян',
    description_az: 'Yanıq qabığı və içərisində ipək kimi axıcı kremli pendiri ilə məşhur Bask çizkeyki. İsti Belçika şokoladı ilə servis olunur.',
    description_en: 'Famous Basque burnt cheesecake with a caramelized crust and gooey molten cream center, served with warm Belgian chocolate.',
    description_ru: 'Баскский обожженный чизкейк с нежнейшей кремовой текстурой, подается с теплым бельгийским шоколадом.',
    base_price: 9.0,
    sizes: [
      { name: 'Portion', volume: '180g', price: 9.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?auto=format&fit=crop&w=800&q=80',
    is_featured: false,
    is_available: true,
    tags: ['Artisan Dessert', 'Must Try'],
    display_order: 8,
  },
  {
    id: 'prod-9',
    category_id: 'cat-4',
    name_az: 'Pistachio Cruffin',
    name_en: 'Pistachio Cruffin',
    name_ru: 'Краффин с фисташкой',
    description_az: 'Kruasan və mafin kəsişməsində qat-qat xırtıldayan xəmir, bol püstəli krem ilə.',
    description_en: 'Flaky laminated croissant-muffin hybrid loaded with roasted pistachio custard cream.',
    description_ru: 'Хрустящий слоеный гибрид круассана и маффина с нежнейшим фисташковым заварным кремом.',
    base_price: 7.0,
    sizes: [
      { name: 'Piece', volume: '140g', price: 7.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    is_featured: false,
    is_available: true,
    tags: ['Bakery'],
    display_order: 9,
  },
  {
    id: 'prod-10',
    category_id: 'cat-5',
    name_az: 'Avocado & Poached Egg Brioche',
    name_en: 'Avocado & Poached Egg Brioche',
    name_ru: 'Бриошь с авокадо и яйцом пашот',
    description_az: 'Qızardılmış kərə yağlı brioş çörəyi, təzə avokado kremı, paşot yumurtası və hollandez sousu.',
    description_en: 'Toasted artisan butter brioche topped with fresh smashed avocado, organic poached egg, and microgreens.',
    description_ru: 'Поджаренная сливочная бриошь, пюре из спелого авокадо, яйцо пашот и микрозелень.',
    base_price: 11.5,
    sizes: [
      { name: 'Portion', volume: '260g', price: 11.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    is_featured: false,
    is_available: true,
    tags: ['Breakfast', 'Fresh'],
    display_order: 10,
  },
];

export const INITIAL_GALLERY: GalleryImage[] = [
  {
    id: 'gal-1',
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=85',
    caption_az: 'RoastBar espresso barı və barista məkanı',
    caption_en: 'RoastBar specialty espresso bar and artisan workstation',
    caption_ru: 'Эспрессо-бар RoastBar и рабочая зона бариста',
    display_order: 1,
  },
  {
    id: 'gal-2',
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=85',
    caption_az: 'İsti və sakit oturma guşəsi, Şihali Qurbanov 2/15',
    caption_en: 'Warm, cozy lounge corner for relaxed conversations & work',
    caption_ru: 'Уютный уголок для отдыха и продуктивной работы',
    display_order: 2,
  },
  {
    id: 'gal-3',
    image_url: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=85',
    caption_az: 'Təzə qovrulmuş seçilmiş qəhvə dənələri',
    caption_en: 'Freshly roasted specialty beans from leading origins',
    caption_ru: 'Свежеобжаренные спешелти зерна со всего мира',
    display_order: 3,
  },
  {
    id: 'gal-4',
    image_url: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1200&q=85',
    caption_az: 'Axşam ab-havası və isti işıqlandırma',
    caption_en: 'Intimate evening ambiance and warm architectural lighting',
    caption_ru: 'Вечерняя атмосфера и теплое камерное освещение',
    display_order: 4,
  },
  {
    id: 'gal-5',
    image_url: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1200&q=85',
    caption_az: 'Günün hər saatında xüsusi anlar',
    caption_en: 'Crafting exceptional coffee moments all day long',
    caption_ru: 'Идеальные кофейные моменты каждый день',
    display_order: 5,
  },
  {
    id: 'gal-6',
    image_url: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?auto=format&fit=crop&w=1200&q=85',
    caption_az: 'RoastBar daxili interyer dizaynı',
    caption_en: 'Modern boutique aesthetic and botanical coffee bar design',
    caption_ru: 'Современный дизайн кофейни и живые растения',
    display_order: 6,
  },
];

